version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    depends_on:
      - pg
    container_name: app-backend-node
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - DB_HOST=pg
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SCHEMA=${DB_SCHEMA}
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app/

  pg:
    image: postgres:16
    container_name: pg-db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
    command: -p ${DB_PORT}
